1234-00:
  item_title: server-1
  item_type: connection
  item_description: server 1
  icon_name: package-x-generic-symbolic
1234-02:
  item_title: server-2
  item_type: connection
  item_description: server 2
  icon_name: package-x-generic-symbolic